spring:
  cloud:
    gcp:
      project-id: ${GCP-PROJECT-ID:test}
      credentials:
        encoded-key: ${GCP_CREDENTIALS:test}
  datasource:
    url: jdbc:postgresql://${CONSUMER-SERVICE-DB-IP}:5432/${CONSUMER-SERVICE-DB-NAME}
    username: ${CONSUMER-SERVICE-DB-USERNAME}
    password: ${CONSUMER-SERVICE-DB-PASSWORD}
    driver:
      class:
        name: org.postgresql.Driver
security:
  api-key: ${CONSUMER-SERVICE-API-KEY:test}
